### ISSUE TITLE
Fix the window SSLError

### ISSUE THREAD

**Issue by Pkoiralap** [NASA-IMPACT/csdap-bulk-download#14]
# Motivation #

The bulk download script fails when ran from windows. This looks like a SSL issue. This is the error log:
```
D:\>csdap-bulk-download f:\dsms\order_356.csv -o f:\dsms\
Earthdata Login username: jstoker
Earthdata Login password:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 248, in _get_conn
    return conn or self._new_conn()
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='csdap.earthdata.nasa.gov', port=443): Max retries exceeded with url: /api/v1/auth/?redirect_uri=script (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\Scripts\csdap-bulk-download.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\csdap_bulk_download\cli.py", line 110, in cli
    token = csdap.get_auth_token(username, password)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\csdap_bulk_download\csdap.py", line 31, in get_auth_token
    allow_redirects=False,
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jstoker\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='csdap.earthdata.nasa.gov', port=443): Max retries exceeded with url: /api/v1/auth/?redirect_uri=script (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

Here is SO question that asks about this issue:
`https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module/55632553#55632553`

# Tasks #

- [ ] Replicate the issue
- [ ] Figure out the root cause of the issue and fix it
- [ ] If the fix can be shipped with the code, change the code, otherwise write a comprehensive doc that describes how to fix the issue in case it arrises.

# Acceptance Criteria #
- [ ] Pull Request with either the fix or a comprehensive document that explains the fix

**Comment by meghana-paramesh** [comment]
@Pkoiralap Please help us with the below questions:
1. csdap-bulk-download f:\dsms\order_356.csv -o f:\dsms\
 where could we get this file order_356.csv from for executing the above command?
 
 2. And also is the password blank or we have a password?

**Comment by meghana-paramesh** [comment]
There are the steps to run the application successfully in a windows machine:
1. Create an account here https://urs.earthdata.nasa.gov/users/new
2. After running the setup.py file (command: python setup.py install), put your username and password when prompted
3. Once the username and password is filled, you would get the below error
`Earthdata Login username: meghananp1
Earthdata Login password:
Traceback (most recent call last):
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\Scripts\csdap-bulk-download-script.py", line 33, in <module>
    sys.exit(load_entry_point('csdap-bulk-download==1.0', 'console_scripts', 'csdap-bulk-download')())
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\cli.py", line 110, in cli
    token = csdap.get_auth_token(username, password)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\csdap.py", line 71, in get_auth_token
    raise AuthError(querystring["error_msg"])
csdap_bulk_download.exceptions.AuthError: ['Pre authorization required for this application, please authorize by visiting the resolution url']`
4. To resolve this error, go to the resolution url as suggested in the error>. Find example resolution url below
`csdap_bulk_download.exceptions.AuthError: https://csdap.earthdata.nasa.gov/api/v1/auth/complete?error=access_denied&state=script&error_msg=Pre authorization required for this application, please authorize by visiting the resolution url&resolution_url=https://urs.earthdata.nasa.gov/approve_app?client_id=N99GqJO2jik_BOKRqUMeUA`
5. Login to the resultion url and agree the terms
![Screenshot (7)](https://user-images.githubusercontent.com/98418669/152405174-18358293-c552-4cf7-a984-080ad79c19c7.png)
6. Then the application would be successfully executed on your windows machine
`(.venv) C:\Users\megha\Documents\hello_django\csdap-bulk-download-main>csdap-bulk-download order_356.csv -o \test
Earthdata Login username: meghananp1
Earthdata Login password:
Complete.`

**Comment by alukach** [comment]
@meghana-paramesh Can you share your reasoning as to why this was closed?

**Comment by Pkoiralap** [comment]
@alukach we could not replicate this issue. It needs more information about the exact specs of the machine that shows this kind of error. In case that is identified, we can create a new issue with updated details.

**Comment by alukach** [comment]
Okay.  Just to log some details from my investigation earlier, this appears to be an issue when using the module with Anaconda.  Some possible fixes:

* https://stackoverflow.com/a/55632553
* https://stackoverflow.com/a/54932141
* https://stackoverflow.com/a/60551653

It would be worthwhile to note what we have attempted when trying to reproduce the error.  Were we able to install the module on Windows using Anaconda?

**Comment by meghana-paramesh** [comment]
@alukach As it was not mentioned earlier that the issue was due to using the module with Anaconda. I just installed everything in setup.py and directly ran the project on a host OS and on a VM with Windows 10 installed on both, by using VS code as the IDE. Hence probably we are unable to replicate. Can you please another issue with the details below or update the same issue and open it again (I am not sure of we can open the closed issue again though)
1. The issue was due to using the module with Anaconda
2. The specs of the machine where the issue was identified

**Comment by alukach** [comment]
I can re-open this if we think that is the best outcome. 

I am inferring that it was an Anaconda-related based on: 

1. Reviewing the path in the above stack trace (`"c:\programdata\`**`anaconda3`**`\lib\site-packages\urllib3\connectionpool.py"`)
2. When searching Google for `urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.`, I find a number of Anaconda-related StackOverflow tickets.

I am not aware of the machine's specs beyond what we are able to infer from the stacktrace (it's a windows machine using an anaconda environment).

**Comment by zacharyDez** [comment]
@alukach should we move the status to backlog?

**Comment by zacharyDez** [comment]
Moved to the backlog, and we can see if we prioritize it or, if it is not relevant, remove it. cc: @alukach
