### ISSUE TITLE
Fix the "Pre authorization required for this application, please authorize by visiting the resolution url" issue

### ISSUE THREAD

**Issue by meghana-paramesh** [NASA-IMPACT/csdap-bulk-download#15]
(.venv) C:\Users\megha\Documents\hello_django\csdap-bulk-download-main>csdap-bulk-download order_356.csv -o \
Earthdata Login username: meghananp
Earthdata Login password:
Traceback (most recent call last):
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\Scripts\csdap-bulk-download-script.py", line 33, in <module>
    sys.exit(load_entry_point('csdap-bulk-download==1.0', 'console_scripts', 'csdap-bulk-download')())
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\cli.py", line 110, in cli
    token = csdap.get_auth_token(username, password)
  File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\csdap.py", line 71, in get_auth_token
    raise AuthError(querystring["error_msg"])
csdap_bulk_download.exceptions.AuthError: ['Pre authorization required for this application, please authorize by visiting the resolution url']

Above error is being thrown because there is no proper flow followed before starting the download. The user needs to agree to the terms and conditions before starting the download

# Tasks #
- [x] Replicate the issue
- [x] Find the root cause
- [x] Come up with a fix

# Acceptance Criteria #
- [x] Pull Request with either the fix or a comprehensive document that explains the fix

**Comment by meghana-paramesh** [comment]
Steps to replicate the issue

1. Create an account here https://urs.earthdata.nasa.gov/users/new
2. After running the setup.py file (command: python setup.py install), put your username and password when prompted
3. Once the username and password is filled, you would get the below error
Earthdata Login username: meghananp1 Earthdata Login password: Traceback (most recent call last): File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\Scripts\csdap-bulk-download-script.py", line 33, in <module> sys.exit(load_entry_point('csdap-bulk-download==1.0', 'console_scripts', 'csdap-bulk-download')()) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1128, in __call__ return self.main(*args, **kwargs) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1053, in main rv = self.invoke(ctx) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\click\core.py", line 754, in invoke return __callback(*args, **kwargs) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\cli.py", line 110, in cli token = csdap.get_auth_token(username, password) File "C:\Users\megha\Documents\hello_django\csdap-bulk-download-main\.venv\lib\site-packages\csdap_bulk_download\csdap.py", line 71, in get_auth_token raise AuthError(querystring["error_msg"]) csdap_bulk_download.exceptions.AuthError: ['Pre authorization required for this application, please authorize by visiting the resolution url']
4. To resolve this error, go to the resolution url as suggested in the error>. Find example resolution url below
csdap_bulk_download.exceptions.AuthError: https://csdap.earthdata.nasa.gov/api/v1/auth/complete?error=access_denied&state=script&error_msg=Pre authorization required for this application, please authorize by visiting the resolution url&resolution_url=https://urs.earthdata.nasa.gov/approve_app?client_id=N99GqJO2jik_BOKRqUMeUA
5. Login to the resultion url and agree the terms
![resolution_url_issue](https://user-images.githubusercontent.com/98418669/152861470-4db1113c-3874-4b75-a9ae-2efabf90dd38.png)
6. Then the application would be successfully executed on your windows machine
(.venv) C:\Users\megha\Documents\hello_django\csdap-bulk-download-main>csdap-bulk-download order_356.csv -o \test Earthdata Login username: meghananp1 Earthdata Login password: Complete.
